@startuml Diagrama_Objetos

object Usuario {
    id_usuario: 1
    nombre: "Juan"
    apellido: "Pérez"
    correo_electronico: "juan.perez@example.com"
    contrasena: "1234"
    direccion: "Calle Falsa 123"
    telefono: "123456789"
}

object Carrito {
    id_carrito: 101
    id_usuario: 1
}

object Producto {
    id_producto: 501
    nombre: "Laptop"
    descripcion: "Laptop de alta gama"
    precio: 1500.00
    cantidad_stock: 10
}

object ItemCarrito {
    id_item: 1001
    id_carrito: 101
    id_producto: 501
    cantidad: 1
}

object Factura {
    id_factura: 2001
    id_usuario: 1
    fecha: "2024-10-30"
    subtotal: 1500.00
    impuestos: 285.00
    total: 1785.00
}

object Pago {
    id_pago: 3001
    metodo: "Tarjeta de crédito"
    numero_tarjeta: "**** **** **** 1234"
    fecha_expiracion: "12/2026"
    codigo_seguridad: "123"
}

Usuario "tiene" -- Carrito
Carrito "contiene" -- ItemCarrito
ItemCarrito "agregado_a" -- Producto
Usuario "genera" -- Factura
Factura "se_realiza_con" -- Pago
Factura "incluye" -- ItemCarrito

@enduml
